<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net462;net80</TargetFrameworks>
    <IsTestProject>true</IsTestProject>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\p4api.net\MyKey.snk</AssemblyOriginatorKeyFile>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" Version="2.7.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\p4api.net\p4api.net.csproj" />
  </ItemGroup>

</Project>
